# Generated by Django 5.1 on 2024-09-10 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0005_alter_startupdetail_profilepic_pitch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equity_required', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_invested', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='business.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='investorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(blank=True, default='useravatar.png', null=True, upload_to='investor/profilepics/')),
                ('investor_name', models.CharField(max_length=250)),
                ('investor_experince', models.CharField(max_length=250)),
                ('investor_amount', models.CharField(max_length=250)),
                ('investor_detail', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='static/startup/')),
                ('additional_details', models.FileField(blank=True, null=True, upload_to='static/startup/')),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
