# Generated by Django 5.1 on 2024-08-26 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(blank=True, default='image/useravatar.png', null=True, upload_to='media/startup/profilepics/')),
                ('startup_name', models.CharField(max_length=250)),
                ('startup_detail', models.TextField()),
                ('founder_name', models.CharField(max_length=250)),
                ('founder_detail', models.TextField()),
                ('co_founders', models.BooleanField(default=False, max_length=250)),
                ('co_founders_detials', models.TextField()),
                ('team', models.CharField(max_length=250)),
                ('team_details', models.TextField()),
                ('business_model', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='static/startup/')),
                ('additional_details', models.FileField(blank=True, null=True, upload_to='static/startup/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
