# Generated by Django 5.1 on 2024-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupdetail',
            name='co_founders',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='startupdetail',
            name='co_founders_detials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupdetail',
            name='team',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='startupdetail',
            name='team_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
