# Generated by Django 5.1 on 2024-08-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_startupdetail_co_founders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupdetail',
            old_name='co_founders_detials',
            new_name='co_founders_details',
        ),
    ]
