# Generated by Django 5.1 on 2024-08-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_co_founders_detials_startupdetail_co_founders_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupdetail',
            name='profilepic',
            field=models.ImageField(blank=True, default='image/useravatar.png', null=True, upload_to='startup/profilepics/'),
        ),
    ]
